IKC-238 Custom change password page
Consdata/kouncil pull request #284
Opened 2022-12-22 23:12 UTC by pbelke

2022-12-23 13:44 UTC, ynleborg commented on kouncil-frontend/apps/kouncil/project.json
> -      "defaultConfiguration": "development"
is this intentional?

2022-12-27 13:17 UTC, dmejer requested changes

2022-12-27 13:17 UTC, dmejer commented on kouncil-frontend/libs/common-login/src/lib/login/common-login.component.ts
> +         [ngClass]="backend === 'SERVER' ? 'icon-login-container-desktop' : 'icon-login-container-demo'">
Can you use composition? Use <ng-content slots> to pass this, instead of implementing that here.

2022-12-27 13:17 UTC, dmejer commented on kouncil-frontend/libs/common-login/src/lib/login/common-login.component.ts
> +          <br>
<p> instead of breaks?

2022-12-27 13:17 UTC, dmejer commented on kouncil-frontend/libs/common-login/src/lib/login/common-login.component.ts
> +  styleUrls: ['./common-login.component.scss', '../common-login.scss']
i do not like it. I like when 1 component have only 1 css file. You can always sahre css with mixins/import css inside component css file.

2022-12-27 13:17 UTC, dmejer commented on kouncil-frontend/libs/common-login/src/lib/change-password/common-change-password.component.ts
> +         [ngClass]="backend === 'SERVER' ? 'icon-login-container-desktop' : 'icon-login-container-demo'">
Same like i common-login. Use composition.
It will make component less smart and boundary context will be better defined.

2022-12-27 13:17 UTC, dmejer commented on kouncil-frontend/apps/kouncil/src/app/routing/auth.guard.ts
> +      console.log(isAuthenticated);
Is it time to add https://github.com/Consdata/logger ? ;)

2022-12-27 13:18 UTC, dmejer requested changes

2022-12-27 13:18 UTC, dmejer commented on kouncil-backend/src/main/java/com/consdata/kouncil/security/AdUserManager.java
> +    @PostConstruct
something missing?

2022-12-28 12:27 UTC, Pefes approved these changes

2022-12-28 14:33 UTC, dmejer approved these changes

2022-12-28 14:35 UTC, merged