IKC-256 SASL configuration
Consdata/kouncil pull request #288
Opened 2022-12-28 08:49 UTC by pbelke

2022-12-30 15:16 UTC, dmejer requested changes

2022-12-30 15:16 UTC, dmejer commented on kouncil-backend/src/main/java/com/consdata/kouncil/config/KouncilConfiguration.java
> +        log.info("{}", sasl);
Can you log it in one line?

2022-12-30 15:16 UTC, dmejer commented on kouncil-backend/src/main/java/com/consdata/kouncil/config/KouncilConfiguration.java
> +    private List<SaslBrokerConfig> sasl;
there is no information about this in documentation. What is it for?

2023-01-02 07:52 UTC, Pefes approved these changes

2023-01-04 15:41 UTC, merged