IKC-203 Monaco Editor
Consdata/kouncil pull request #312
Opened 2023-07-28 08:52 UTC by pbelke

2023-11-23 07:50 UTC, ynleborg approved these changes

2023-12-06 11:44 UTC, dmejer requested changes
Regression in send event
![image](https://github.com/Consdata/kouncil/assets/4751284/c5316e0f-a3eb-4afa-802e-049788d836e6)

2023-12-06 11:59 UTC, dmejer reviewed
![image](https://github.com/Consdata/kouncil/assets/4751284/48903bb7-44ad-4388-8fbd-6cdd26f95b8e)
We are using json as kafka events. Can we set 'json' form on monaco editor somehow?
https://microsoft.github.io/monaco-editor/

2023-12-11 07:12 UTC, dmejer approved these changes

2024-03-19 17:41 UTC, merged