IKC-316 Mange topics (CRUD)
Consdata/kouncil pull request #325
Opened 2024-01-06 22:01 UTC by pbelke

2024-01-08 13:42 UTC, Pefes requested changes

2024-04-08 11:13 UTC, juris-97 requested changes

2024-04-08 11:13 UTC, juris-97 commented on kouncil-frontend/libs/feat-topics/src/lib/topics/list/topics.component.ts
> +  createTopic(topicName?: string) {
Missing return type 'void'

2024-04-08 11:13 UTC, juris-97 commented on kouncil-frontend/libs/feat-topics/src/lib/topics/list/topics.component.ts
> +    let config = {
This variable can be const

2024-04-08 11:13 UTC, juris-97 commented on kouncil-frontend/libs/feat-topics/src/lib/topics/list/topics.component.ts
> +    let matDialogRef = this.dialog.open(TopicFormComponent, config);
const

2024-04-08 11:13 UTC, juris-97 commented on kouncil-frontend/libs/feat-topics/src/lib/topics/list/topics.component.ts
> +    })
Missing ;

2024-04-08 11:13 UTC, juris-97 commented on kouncil-frontend/libs/feat-topics/src/lib/topics/list/topics.component.ts
> +    .subscribe(() => {
deprecated usage, instead use: 
```
.subscribe({
      next: () => {

      },
      error: error => {

      }
    });
```

2024-04-08 11:13 UTC, juris-97 commented on kouncil-frontend/libs/feat-topics/src/lib/topics/list/topics.demo.service.ts
> +import {TopicsService} from "../topics.service";
Single quotes should be used

2024-04-10 18:34 UTC, pbelke commented on kouncil-frontend/libs/feat-topics/src/lib/topic/topic-data.ts
> +  replicationFactor?: number;
It is being used in the topic form component

2024-04-19 06:35 UTC, juris-97 approved these changes
Looks good!

2024-04-23 10:06 UTC, juris-97 approved these changes

2024-04-23 16:34 UTC, merged